import json
import unittest
from datetime import date
from urllib.parse import parse_qs

import regex_based_graph_night as poker


class FakeResponse:
    def __init__(self, payload):
        self.payload = payload

    def __enter__(self):
        return self

    def __exit__(self, *args):
        return False

    def read(self):
        return json.dumps(self.payload).encode()


class SplitwiseTests(unittest.TestCase):
    def test_choose_poker_night_group(self):
        group = poker._choose_poker_night_group(
            [
                {"id": 1, "name": "Poker Night 2024"},
                {"id": 2, "name": "Poker Night 2025"},
                {"id": 3, "name": "Poker Night Games", "created_at": "2026-01-01T00:00:00Z"},
            ],
            input_fn=lambda prompt: "2",
            output_fn=lambda message: None,
        )
        self.assertEqual(group["id"], 2)

    def test_member_mapping_rejects_duplicate_member(self):
        selections = iter(["alex@example.com", "alex@example.com"])
        with self.assertRaisesRegex(ValueError, "more than once"):
            poker._map_players_to_group_members(
                ["Alex", "Sam"],
                [
                    {"id": 10, "email": "alex@example.com"},
                    {"id": 11, "email": "sam@example.com"},
                ],
                input_fn=lambda prompt: next(selections),
                output_fn=lambda message: None,
            )

    def test_known_player_uses_email_mapping_without_prompting(self):
        mapped = poker._map_players_to_group_members(
            ["Arash"],
            [{"id": 10, "email": "arashrai17@gmail.com"}],
            input_fn=lambda prompt: self.fail("known players should not prompt"),
            output_fn=lambda message: None,
        )
        self.assertEqual(mapped["Arash"]["id"], 10)

    def test_20260715_rebuy_is_included_in_zero_sum_balances(self):
        path = "logs/poker_night_20260715.csv"
        with open(path) as file:
            logs = poker.fix_up_player_names(file.readlines())
        logs.pop(0)
        logs.reverse()
        event = poker.PokerNightEvent(poker.date_of_csv(path), logs)
        history = event.player_stack_history()

        self.assertEqual(history["Prilik"][-1][0], -1600)
        self.assertEqual(sum(entries[-1][0] for entries in history.values()), 0)

    def test_add_expense_uses_profit_as_paid_and_owed_shares(self):
        requests = []
        responses = iter(
            [
                FakeResponse(
                    {
                        "groups": [
                            {
                                "id": 42,
                                "name": "Poker Night",
                                "created_at": "2025-01-01T00:00:00Z",
                                "members": [
                                    {"id": 10, "first_name": "Alex", "last_name": None, "email": "alex@example.com"},
                                    {"id": 11, "first_name": "Sam", "last_name": "", "email": "sam@example.com"},
                                    {"id": 12, "first_name": "George", "last_name": "", "email": "georgeutsin@gmail.com"},
                                ],
                            }
                        ]
                    }
                ),
                FakeResponse({"expenses": []}),
                FakeResponse({"expenses": [{"id": 99}]}),
            ]
        )

        def opener(request, timeout):
            requests.append(request)
            return next(responses)

        history = {
            "Alex": [(150, None)],
            "Sam": [(-100, None)],
            "George": [(-50, None)],
        }
        selections = iter(["1", "alex@example.com", "sam@example.com", "george@example.com"])
        expense = poker.add_splitwise_expense(
            history,
            date(2026, 7, 22),
            "token",
            opener,
            input_fn=lambda prompt: next(selections),
        )

        self.assertEqual(expense["id"], 99)
        payload = parse_qs(requests[2].data.decode())
        self.assertEqual(payload["group_id"], ["42"])
        self.assertEqual(payload["cost"], ["1.50"])
        self.assertEqual(payload["date"], ["2026-07-22"])
        self.assertEqual(payload["details"], ["Generated by the poker-with-the-boys script"])
        self.assertEqual(payload["currency_code"], ["CAD"])
        self.assertEqual(payload["users__0__user_id"], ["10"])
        self.assertEqual(payload["users__0__paid_share"], ["1.50"])
        self.assertEqual(payload["users__0__owed_share"], ["0.00"])
        self.assertEqual(payload["users__1__user_id"], ["11"])
        self.assertEqual(payload["users__1__paid_share"], ["0.00"])
        self.assertEqual(payload["users__1__owed_share"], ["1.00"])
        self.assertEqual(payload["users__2__user_id"], ["12"])
        self.assertEqual(payload["users__2__owed_share"], ["0.50"])

    def test_existing_expense_warns_and_skips_creation(self):
        requests = []
        responses = iter(
            [
                FakeResponse(
                    {
                        "groups": [
                            {
                                "id": 42,
                                "name": "Poker Night",
                                "created_at": "2025-01-01T00:00:00Z",
                                "members": [],
                            }
                        ]
                    }
                ),
                FakeResponse(
                    {
                        "expenses": [
                            {
                                "id": 98,
                                "description": "Poker Night 2026-07-22",
                                "date": "2026-07-22T00:00:00Z",
                            }
                        ]
                    }
                ),
            ]
        )

        def opener(request, timeout):
            requests.append(request)
            return next(responses)

        history = {"Alex": [(150, None)], "Sam": [(-150, None)]}
        with self.assertWarnsRegex(RuntimeWarning, "already exists"):
            result = poker.add_splitwise_expense(
                history,
                date(2026, 7, 22),
                "token",
                opener,
                input_fn=lambda prompt: "1",
            )

        self.assertIsNone(result)
        self.assertEqual(len(requests), 2)


if __name__ == "__main__":
    unittest.main()
